### ISSUE TITLE
Add resistor for the Tubes

### ISSUE THREAD

**Issue by rnestler** [coredump-ch/nixie-counter#18] opened 2020-01-20 08:20 UTC
@dbrgn Did you already do this?

**Comment by dbrgn** [comment] 2020-01-20 08:29
Yes, but I haven't pushed it yet. I first want to solder in a resistor manually to test whether it works as intended. If that's the case, I'll probably order new PCBs.

**Comment by dbrgn** [comment] 2020-02-03 23:08
Fixed in 6192590d353f609020a5828986d185787f941594

**Closed as completed by dbrgn** 2020-02-03 23:08 UTC
